<?php
require_once 'includes/header.php';

// --- A Button to Test the System ---
if (isset($_GET['trigger_test'])) {
    trigger_error("[TEST] This is a simulated Warning generated by the Developer.", E_USER_WARNING);
    // Let's also trigger a noticeable notice
    $undefined_variable_test = $this_variable_does_not_exist; 
    
    // Redirect to clear URL parameters
    echo "<script>window.location.href='error_logs.php';</script>";
    exit();
}

// Clear logs action
if (isset($_GET['clear']) && $_GET['clear'] == 'all') {
    $conn->query("TRUNCATE TABLE error_logs");
    header("Location: error_logs.php");
    exit();
}

// --- Filtering ---
$where = [];
$params = [];
$types = "";

if (isset($_GET['search']) && !empty($_GET['search'])) {
    $where[] = "(error_message LIKE ? OR file_path LIKE ?)";
    $params[] = "%".$_GET['search']."%";
    $params[] = "%".$_GET['search']."%";
    $types .= "ss";
}

$sql = "SELECT * FROM error_logs";
if (!empty($where)) {
    $sql .= " WHERE " . implode(" AND ", $where);
}
$sql .= " ORDER BY id DESC LIMIT 200";

$stmt = $conn->prepare($sql);
if(!empty($params)){
    $stmt->bind_param($types, ...$params);
}
$stmt->execute();
$result = $stmt->get_result();
?>

<div class="card">
    <div style="display:flex; justify-content:space-between; align-items:flex-end; margin-bottom:1.5rem; flex-wrap:wrap; gap:1rem;">
        <div>
            <h2>System Error Logs</h2>
            <p style="color:var(--text-muted); margin:0;">Captures PHP errors, warnings, and notices automatically.</p>
        </div>
        
        <div style="display:flex; gap:10px;">
             <!-- Test Button -->
             <a href="error_logs.php?trigger_test=1" class="btn btn-warning btn-sm">
                <i class="fas fa-bug"></i> Trigger Test Error
            </a>
            
             <!-- Clear Button -->
            <a href="error_logs.php?clear=all" class="btn btn-danger btn-sm" onclick="return confirm('Clear all error logs?');">
                <i class="fas fa-trash"></i> Clear All
            </a>
        </div>
    </div>
    
    <!-- Search Bar -->
    <form method="GET" style="margin-bottom:1.5rem; display:flex; gap:10px;">
        <input type="text" name="search" class="form-control" placeholder="Search error message or filename..." value="<?php echo isset($_GET['search']) ? htmlspecialchars($_GET['search']) : ''; ?>">
        <button type="submit" class="btn btn-primary">Search</button>
        <?php if(isset($_GET['search'])): ?>
            <a href="error_logs.php" class="btn btn-secondary">Reset</a>
        <?php endif; ?>
    </form>
    
    <div class="table-responsive">
    <table>
        <thead>
            <tr>
                <th width="80">Level</th>
                <th>Message</th>
                <th width="300">Location</th>
                <th width="150">Time</th>
            </tr>
        </thead>
        <tbody>
            <?php if ($result && $result->num_rows > 0): while($row = $result->fetch_assoc()): 
                // Color coding for levels
                $lvl = $row['error_level'];
                $badges = [
                    1 => ['bg'=>'#ef4444', 'txt'=>'Fatal'],       // E_ERROR
                    2 => ['bg'=>'#f59e0b', 'txt'=>'Warning'],     // E_WARNING
                    4 => ['bg'=>'#f59e0b', 'txt'=>'Parse'],       // E_PARSE
                    8 => ['bg'=>'#3b82f6', 'txt'=>'Notice'],      // E_NOTICE
                    256 => ['bg'=>'#ef4444', 'txt'=>'User Error'],// E_USER_ERROR
                    512 => ['bg'=>'#f59e0b', 'txt'=>'User Warn'], // E_USER_WARNING
                    1024 => ['bg'=>'#3b82f6', 'txt'=>'User Notice'], // E_USER_NOTICE
                    404 => ['bg'=>'#9333ea', 'txt'=>'404 Hit']     // 404 Not Found
                ];
                // Default fallback
                $b_style = isset($badges[$lvl]) ? $badges[$lvl]['bg'] : '#64748b';
                $b_text = isset($badges[$lvl]) ? $badges[$lvl]['txt'] : 'Err: '.$lvl;
            ?>
            <tr>
                <td style="vertical-align:top;">
                    <span style="background:<?php echo $b_style; ?>; color:white; padding:4px 8px; border-radius:4px; font-size:0.75em; font-weight:600; white-space:nowrap;">
                        <?php echo $b_text; ?>
                    </span>
                </td>
                <td style="color: var(--text-color); font-weight:500; vertical-align:top;">
                    <?php echo htmlspecialchars($row['error_message']); ?>
                </td>
                <td style="vertical-align:top;">
                    <div style="font-size: 0.9em; font-weight:600; color:var(--primary-color);">
                        <i class="far fa-file-code"></i> <?php echo htmlspecialchars(basename($row['file_path'])); ?>:<?php echo $row['line_number']; ?>
                    </div>
                    <div style="font-size: 0.8em; color:var(--text-muted); margin-top:4px;">
                        path: <?php echo htmlspecialchars($row['request_url']); ?>
                    </div>
                </td>
                <td style="white-space:nowrap; font-size:0.85em; color:var(--text-muted); vertical-align:top;">
                    <?php echo date('M d, H:i:s', strtotime($row['created_at'])); ?>
                </td>
            </tr>
            <?php endwhile; else: ?>
            <tr><td colspan="4" style="text-align:center; padding:3rem; color:var(--success);">
                <i class="fas fa-check-circle" style="font-size:2rem; margin-bottom:1rem; display:block; opacity:0.5;"></i>
                No errors found immediately. 
                <br><small style="color:var(--text-muted)">Click "Trigger Test Error" to verify functionality.</small>
            </td></tr>
            <?php endif; ?>
        </tbody>
    </table>
    </div>
</div>

<?php require_once 'includes/footer.php'; ?>
