@echo off
REM ============================================================
REM DEPLOY - Diagnostic Center (Run on ANY machine)
REM ============================================================
REM This script sets up everything on a fresh machine:
REM   - Pulls the image from Docker Hub
REM   - Asks how you want to access the website
REM   - Creates the database
REM   - Starts all containers (auto-start on boot)
REM
REM Requirements: Docker Desktop installed and running
REM ============================================================

setlocal enabledelayedexpansion

echo.
echo ============================================================
echo   Diagnostic Center - One-Click Deploy
echo ============================================================
echo.

REM ---- Check Docker ----
docker --version >nul 2>&1
if %errorlevel% neq 0 (
    echo ERROR: Docker is not installed!
    echo Download from: https://www.docker.com/products/docker-desktop
    echo After installing, restart this script.
    pause
    exit /b 1
)

REM ---- Check if Docker daemon is running ----
docker info >nul 2>&1
if %errorlevel% neq 0 (
    echo ERROR: Docker is installed but NOT running!
    echo Please start Docker Desktop and wait for it to be ready.
    pause
    exit /b 1
)

echo Docker is running. Good!
echo.

REM ---- Pre-flight port check ----
echo Checking for port conflicts...
set PORT_CONFLICT=0
for %%P in (8081 8443 3301 8082) do (
    for /f "tokens=5" %%i in ('netstat -ano ^| findstr ":%%P " ^| findstr "LISTENING" 2^>nul') do (
        echo   [WARNING] Port %%P is already in use by PID %%i
        set PORT_CONFLICT=1
    )
)
if %PORT_CONFLICT%==1 (
    echo.
    echo   Some ports are in use. Docker may fail to bind.
    echo   Default ports: 8081 ^(HTTP^), 8443 ^(HTTPS^), 3301 ^(DB^), 8082 ^(PMA^)
    echo   These avoid conflict with system Apache on 80/443.
    echo.
    set /p CONTINUE_ANYWAY="Continue anyway? (y/n): "
    if /i not "!CONTINUE_ANYWAY!"=="y" exit /b 1
) else (
    echo   All ports free. No conflicts with system Apache 2.4.
)
echo.

REM ---- Choose access mode ----
echo How do you want to access this website?
echo.
echo   1. Localhost only     (http://localhost:8081)
echo   2. Private/Local IP   (e.g., http://192.168.1.100:8081)
echo   3. Public IP          (e.g., http://203.45.67.89:8081)
echo   4. Domain name        (e.g., http://mysite.com)
echo.
set /p mode="Enter choice (1/2/3/4): "

set SERVER_NAME=localhost

if "%mode%"=="1" (
    set SERVER_NAME=localhost
    echo.
    echo   Using: localhost
)
if "%mode%"=="2" (
    echo.
    echo Your local IP addresses:
    for /f "tokens=2 delims=:" %%a in ('ipconfig ^| findstr /c:"IPv4"') do echo    %%a
    echo.
    set /p SERVER_NAME="Enter your private IP (e.g., 192.168.1.100): "
)
if "%mode%"=="3" (
    echo.
    echo   TIP: Find your public IP at https://whatismyip.com
    echo   Make sure port 8081 is forwarded in your router.
    echo.
    set /p SERVER_NAME="Enter your public IP: "
)
if "%mode%"=="4" (
    echo.
    set /p SERVER_NAME="Enter your domain name (e.g., mysite.com): "
)

echo.
echo   Server Name: %SERVER_NAME%

REM ---- Set database password ----
echo.
set /p DB_PASSWORD="Set database password (press Enter for 'root_password'): "
if "%DB_PASSWORD%"=="" set DB_PASSWORD=root_password

REM ---- Create deploy directory ----
set DEPLOY_DIR=%~dp0
echo.
echo   Deploy location: %DEPLOY_DIR%

REM ---- Create .env file ----
echo.
echo Creating configuration...

(
echo # Diagnostic Center - Configuration
echo # Auto-generated by deploy.bat
echo.
echo APP_PORT=8081
echo SSL_PORT=8443
echo PMA_PORT=8082
echo DB_PORT=3301
echo DB_BIND_IP=127.0.0.1
echo PMA_BIND_IP=127.0.0.1
echo.
echo DB_HOST=db
echo DB_USER=root
echo DB_PASS=%DB_PASSWORD%
echo DB_NAME=diagnostic_center_db
echo.
echo DB_EXTRA_USER=diagnostic_user
echo DB_EXTRA_PASS=diagnostic_pass
echo.
echo APACHE_SERVER_NAME=%SERVER_NAME%
echo ENABLE_SSL=false
echo.
echo # ---- Public IP Configuration ----
echo PUBLIC_IP=
echo LOCAL_IP=
echo DUAL_IP_BIND=true
echo IP_CHECK_INTERVAL=300
echo INIT_BUNDLE_GUARD=true
) > "%DEPLOY_DIR%.env"

echo   .env file created

REM ---- Create docker-compose.yml for pull-only deploy ----
REM (This version uses the pre-built image from Docker Hub, no build needed)

(
echo # ============================================================
echo # Diagnostic Center - Docker Compose ^(Deploy Mode^)
echo # ============================================================
echo # This pulls the pre-built image from Docker Hub.
echo # Auto-generated by deploy.bat
echo # ============================================================
echo.
echo services:
echo   web:
echo     image: ratnachand/diagnostic-center-web:latest
echo     container_name: diagnostic-center-web
echo     restart: always
echo     ports:
echo       - "${APP_PORT:-8081}:80"
echo       - "${SSL_PORT:-8443}:443"
echo     environment:
echo       - DB_HOST=${DB_HOST:-db}
echo       - DB_USER=${DB_USER:-root}
echo       - DB_PASS=${DB_PASS:-root_password}
echo       - DB_NAME=${DB_NAME:-diagnostic_center_db}
echo       - APACHE_SERVER_NAME=${APACHE_SERVER_NAME:-localhost}
echo       - ENABLE_SSL=${ENABLE_SSL:-false}
echo       - INIT_BUNDLE_GUARD=${INIT_BUNDLE_GUARD:-true}
echo     volumes:
echo       - uploads_data:/var/www/html/uploads
echo       - saved_bills_data:/var/www/html/saved_bills
echo       - final_reports_data:/var/www/html/final_reports
echo       - manager_uploads_data:/var/www/html/manager/uploads
echo       - dump_backup_data:/var/www/html/dump/backup
echo       - ssl_certs:/etc/apache2/ssl
echo     depends_on:
echo       db:
echo         condition: service_healthy
echo     networks:
echo       - diagnostic-net
echo.
echo   db:
echo     image: mariadb:10.4
echo     container_name: diagnostic-center-db
echo     restart: always
echo     environment:
echo       - MYSQL_ROOT_PASSWORD=${DB_PASS:-root_password}
echo       - MYSQL_DATABASE=${DB_NAME:-diagnostic_center_db}
echo       - MYSQL_USER=${DB_EXTRA_USER:-diagnostic_user}
echo       - MYSQL_PASSWORD=${DB_EXTRA_PASS:-diagnostic_pass}
echo     ports:
echo       - "${DB_BIND_IP:-127.0.0.1}:${DB_PORT:-3301}:3306"
echo     volumes:
echo       - db_data:/var/lib/mysql
echo       - ./dump/init:/docker-entrypoint-initdb.d:ro
echo     healthcheck:
echo       test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASS:-root_password}"]
echo       interval: 10s
echo       timeout: 5s
echo       retries: 5
echo       start_period: 30s
echo     networks:
echo       - diagnostic-net
echo.
echo   phpmyadmin:
echo     image: phpmyadmin/phpmyadmin:latest
echo     container_name: diagnostic-center-pma
echo     restart: always
echo     ports:
echo       - "${PMA_BIND_IP:-127.0.0.1}:${PMA_PORT:-8082}:80"
echo     environment:
echo       - PMA_HOST=db
echo       - PMA_USER=root
echo       - PMA_PASSWORD=${DB_PASS:-root_password}
echo       - UPLOAD_LIMIT=100M
echo     depends_on:
echo       db:
echo         condition: service_healthy
echo     networks:
echo       - diagnostic-net
echo.
echo volumes:
echo   db_data:
echo   uploads_data:
echo   saved_bills_data:
echo   final_reports_data:
echo   manager_uploads_data:
echo   dump_backup_data:
echo   ssl_certs:
echo.
echo networks:
echo   diagnostic-net:
echo     driver: bridge
) > "%DEPLOY_DIR%docker-compose.deploy.yml"

REM ---- Pull images ----
echo.
echo Pulling Docker images (this may take a few minutes)...
docker compose -f "%DEPLOY_DIR%docker-compose.deploy.yml" pull

REM ---- Import SQL database if init files exist ----
if exist "%DEPLOY_DIR%dump\init\*.sql" (
    echo.
    echo Loading database schema...
    REM Start only db first
    docker compose -f "%DEPLOY_DIR%docker-compose.deploy.yml" --env-file "%DEPLOY_DIR%.env" up -d db
    
    echo Waiting for database to be ready...
    :waitdb
    docker exec diagnostic-center-db mysqladmin ping -h localhost -u root -p%DB_PASSWORD% >nul 2>&1
    if %errorlevel% neq 0 (
        timeout /t 3 /nobreak >nul
        goto waitdb
    )
    echo   Database is ready.
    
    REM Check if database already has tables
    for /f %%i in ('docker exec diagnostic-center-db mysql -u root -p%DB_PASSWORD% -N -e "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='diagnostic_center_db'" 2^>nul') do set TABLE_COUNT=%%i
    
    if "%TABLE_COUNT%"=="0" (
        echo   Importing SQL init files from dump\init\ ...
        set IMPORT_FAILED=0
        for %%F in ("%DEPLOY_DIR%dump\init\*.sql") do (
            echo      - %%~nxF
            docker exec -i diagnostic-center-db mysql -u root -p%DB_PASSWORD% diagnostic_center_db < "%%F"
            if errorlevel 1 (
                set IMPORT_FAILED=1
                echo   WARNING: Failed to import %%~nxF
            )
        )
        if "!IMPORT_FAILED!"=="0" (
            echo   Database imported successfully!
        ) else (
            echo   WARNING: One or more SQL files failed to import. Check manually via phpMyAdmin.
        )
    ) else (
        echo   Database already has %TABLE_COUNT% tables, skipping import.
    )
) else (
    echo.
    echo NOTE: No SQL init files found. Database will be empty.
    echo   Place SQL init files in dump\init\ and re-run to import.
)

REM ---- Start all containers ----
echo.
echo Starting all services...
docker compose -f "%DEPLOY_DIR%docker-compose.deploy.yml" --env-file "%DEPLOY_DIR%.env" up -d

REM ---- Wait and verify ----
echo.
echo Waiting for services to be ready...
timeout /t 10 /nobreak >nul

echo.
echo Checking container status...
docker compose -f "%DEPLOY_DIR%docker-compose.deploy.yml" ps

echo.
echo ============================================================
echo   DEPLOYMENT COMPLETE!
echo ============================================================
echo.
echo   Website:    http://%SERVER_NAME%:8081
echo   phpMyAdmin: http://%SERVER_NAME%:8082
echo.
echo   All containers will AUTO-START when Windows boots.
echo   (Docker Desktop must be set to start with Windows)
echo.
echo   TIP: Make sure Docker Desktop is set to:
echo     Settings ^> General ^> "Start Docker Desktop when you sign in"
echo ============================================================
echo.
pause
